/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.control;

/**
Builder class for javafx.scene.control.ButtonBase
@see javafx.scene.control.ButtonBase
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public abstract class ButtonBaseBuilder<B extends javafx.scene.control.ButtonBaseBuilder<B>> extends javafx.scene.control.LabeledBuilder<B> {
    protected ButtonBaseBuilder() {
    }


    private boolean __set;
    public void applyTo(javafx.scene.control.ButtonBase x) {
        super.applyTo(x);
        if (__set) x.setOnAction(this.onAction);
    }

    private javafx.event.EventHandler<javafx.event.ActionEvent> onAction;
    /**
    Set the value of the {@link javafx.scene.control.ButtonBase#getOnAction() onAction} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B onAction(javafx.event.EventHandler<javafx.event.ActionEvent> x) {
        this.onAction = x;
        __set = true;
        return (B) this;
    }

}
