/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.control;

/**
Builder class for javafx.scene.control.CheckBox
@see javafx.scene.control.CheckBox
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class CheckBoxBuilder<B extends javafx.scene.control.CheckBoxBuilder<B>> extends javafx.scene.control.ButtonBaseBuilder<B> implements javafx.util.Builder<javafx.scene.control.CheckBox> {
    protected CheckBoxBuilder() {
    }

    /** Creates a new instance of CheckBoxBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.control.CheckBoxBuilder<?> create() {
        return new javafx.scene.control.CheckBoxBuilder();
    }

    private int __set;
    public void applyTo(javafx.scene.control.CheckBox x) {
        super.applyTo(x);
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setAllowIndeterminate(this.allowIndeterminate);
        if ((set & (1 << 1)) != 0) x.setIndeterminate(this.indeterminate);
        if ((set & (1 << 2)) != 0) x.setSelected(this.selected);
    }

    private boolean allowIndeterminate;
    /**
    Set the value of the {@link javafx.scene.control.CheckBox#isAllowIndeterminate() allowIndeterminate} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B allowIndeterminate(boolean x) {
        this.allowIndeterminate = x;
        __set |= 1 << 0;
        return (B) this;
    }

    private boolean indeterminate;
    /**
    Set the value of the {@link javafx.scene.control.CheckBox#isIndeterminate() indeterminate} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B indeterminate(boolean x) {
        this.indeterminate = x;
        __set |= 1 << 1;
        return (B) this;
    }

    private boolean selected;
    /**
    Set the value of the {@link javafx.scene.control.CheckBox#isSelected() selected} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B selected(boolean x) {
        this.selected = x;
        __set |= 1 << 2;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.scene.control.CheckBox} based on the properties set on this builder.
    */
    public javafx.scene.control.CheckBox build() {
        javafx.scene.control.CheckBox x = new javafx.scene.control.CheckBox();
        applyTo(x);
        return x;
    }
}
