/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.control;

/**
Builder class for javafx.scene.control.CheckMenuItem
@see javafx.scene.control.CheckMenuItem
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class CheckMenuItemBuilder<B extends javafx.scene.control.CheckMenuItemBuilder<B>> extends javafx.scene.control.MenuItemBuilder<B> {
    protected CheckMenuItemBuilder() {
    }

    /** Creates a new instance of CheckMenuItemBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.control.CheckMenuItemBuilder<?> create() {
        return new javafx.scene.control.CheckMenuItemBuilder();
    }

    private boolean __set;
    public void applyTo(javafx.scene.control.CheckMenuItem x) {
        super.applyTo(x);
        if (__set) x.setSelected(this.selected);
    }

    private boolean selected;
    /**
    Set the value of the {@link javafx.scene.control.CheckMenuItem#isSelected() selected} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B selected(boolean x) {
        this.selected = x;
        __set = true;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.scene.control.CheckMenuItem} based on the properties set on this builder.
    */
    public javafx.scene.control.CheckMenuItem build() {
        javafx.scene.control.CheckMenuItem x = new javafx.scene.control.CheckMenuItem();
        applyTo(x);
        return x;
    }
}
