/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.control;

/**
Builder class for javafx.scene.control.CustomMenuItem
@see javafx.scene.control.CustomMenuItem
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class CustomMenuItemBuilder<B extends javafx.scene.control.CustomMenuItemBuilder<B>> extends javafx.scene.control.MenuItemBuilder<B> {
    protected CustomMenuItemBuilder() {
    }

    /** Creates a new instance of CustomMenuItemBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.control.CustomMenuItemBuilder<?> create() {
        return new javafx.scene.control.CustomMenuItemBuilder();
    }

    private int __set;
    public void applyTo(javafx.scene.control.CustomMenuItem x) {
        super.applyTo(x);
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setContent(this.content);
        if ((set & (1 << 1)) != 0) x.setHideOnClick(this.hideOnClick);
    }

    private javafx.scene.Node content;
    /**
    Set the value of the {@link javafx.scene.control.CustomMenuItem#getContent() content} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B content(javafx.scene.Node x) {
        this.content = x;
        __set |= 1 << 0;
        return (B) this;
    }

    private boolean hideOnClick;
    /**
    Set the value of the {@link javafx.scene.control.CustomMenuItem#isHideOnClick() hideOnClick} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B hideOnClick(boolean x) {
        this.hideOnClick = x;
        __set |= 1 << 1;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.scene.control.CustomMenuItem} based on the properties set on this builder.
    */
    public javafx.scene.control.CustomMenuItem build() {
        javafx.scene.control.CustomMenuItem x = new javafx.scene.control.CustomMenuItem();
        applyTo(x);
        return x;
    }
}
