/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.control;

/**
Builder class for javafx.scene.control.Hyperlink
@see javafx.scene.control.Hyperlink
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class HyperlinkBuilder<B extends javafx.scene.control.HyperlinkBuilder<B>> extends javafx.scene.control.ButtonBaseBuilder<B> implements javafx.util.Builder<javafx.scene.control.Hyperlink> {
    protected HyperlinkBuilder() {
    }

    /** Creates a new instance of HyperlinkBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.control.HyperlinkBuilder<?> create() {
        return new javafx.scene.control.HyperlinkBuilder();
    }

    private boolean __set;
    public void applyTo(javafx.scene.control.Hyperlink x) {
        super.applyTo(x);
        if (__set) x.setVisited(this.visited);
    }

    private boolean visited;
    /**
    Set the value of the {@link javafx.scene.control.Hyperlink#isVisited() visited} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B visited(boolean x) {
        this.visited = x;
        __set = true;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.scene.control.Hyperlink} based on the properties set on this builder.
    */
    public javafx.scene.control.Hyperlink build() {
        javafx.scene.control.Hyperlink x = new javafx.scene.control.Hyperlink();
        applyTo(x);
        return x;
    }
}
