/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.control;

/**
Builder class for javafx.scene.control.Label
@see javafx.scene.control.Label
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class LabelBuilder<B extends javafx.scene.control.LabelBuilder<B>> extends javafx.scene.control.LabeledBuilder<B> implements javafx.util.Builder<javafx.scene.control.Label> {
    protected LabelBuilder() {
    }

    /** Creates a new instance of LabelBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.control.LabelBuilder<?> create() {
        return new javafx.scene.control.LabelBuilder();
    }

    private boolean __set;
    public void applyTo(javafx.scene.control.Label x) {
        super.applyTo(x);
        if (__set) x.setLabelFor(this.labelFor);
    }

    private javafx.scene.Node labelFor;
    /**
    Set the value of the {@link javafx.scene.control.Label#getLabelFor() labelFor} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B labelFor(javafx.scene.Node x) {
        this.labelFor = x;
        __set = true;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.scene.control.Label} based on the properties set on this builder.
    */
    public javafx.scene.control.Label build() {
        javafx.scene.control.Label x = new javafx.scene.control.Label();
        applyTo(x);
        return x;
    }
}
