/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.control;

/**
Builder class for javafx.scene.control.ListCell
@see javafx.scene.control.ListCell
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class ListCellBuilder<T, B extends javafx.scene.control.ListCellBuilder<T, B>> extends javafx.scene.control.IndexedCellBuilder<T, B> {
    protected ListCellBuilder() {
    }

    /** Creates a new instance of ListCellBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static <T> javafx.scene.control.ListCellBuilder<T, ?> create() {
        return new javafx.scene.control.ListCellBuilder();
    }

    /**
    Make an instance of {@link javafx.scene.control.ListCell} based on the properties set on this builder.
    */
    public javafx.scene.control.ListCell<T> build() {
        javafx.scene.control.ListCell<T> x = new javafx.scene.control.ListCell<T>();
        applyTo(x);
        return x;
    }
}
