/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.control;

/**
Builder class for javafx.scene.control.MenuButton
@see javafx.scene.control.MenuButton
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class MenuButtonBuilder<B extends javafx.scene.control.MenuButtonBuilder<B>> extends javafx.scene.control.ButtonBaseBuilder<B> implements javafx.util.Builder<javafx.scene.control.MenuButton> {
    protected MenuButtonBuilder() {
    }

    /** Creates a new instance of MenuButtonBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.control.MenuButtonBuilder<?> create() {
        return new javafx.scene.control.MenuButtonBuilder();
    }

    private int __set;
    public void applyTo(javafx.scene.control.MenuButton x) {
        super.applyTo(x);
        int set = __set;
        if ((set & (1 << 0)) != 0) x.getItems().addAll(this.items);
        if ((set & (1 << 1)) != 0) x.setPopupSide(this.popupSide);
    }

    private java.util.Collection<? extends javafx.scene.control.MenuItem> items;
    /**
    Add the given items to the List of items in the {@link javafx.scene.control.MenuButton#getItems() items} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B items(java.util.Collection<? extends javafx.scene.control.MenuItem> x) {
        this.items = x;
        __set |= 1 << 0;
        return (B) this;
    }

    /**
    Add the given items to the List of items in the {@link javafx.scene.control.MenuButton#getItems() items} property for the instance constructed by this builder.
    */
    public B items(javafx.scene.control.MenuItem... x) {
        return items(java.util.Arrays.asList(x));
    }

    private javafx.geometry.Side popupSide;
    /**
    Set the value of the {@link javafx.scene.control.MenuButton#getPopupSide() popupSide} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B popupSide(javafx.geometry.Side x) {
        this.popupSide = x;
        __set |= 1 << 1;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.scene.control.MenuButton} based on the properties set on this builder.
    */
    public javafx.scene.control.MenuButton build() {
        javafx.scene.control.MenuButton x = new javafx.scene.control.MenuButton();
        applyTo(x);
        return x;
    }
}
