/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.control;

/**
Builder class for javafx.scene.control.RadioButton
@see javafx.scene.control.RadioButton
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class RadioButtonBuilder<B extends javafx.scene.control.RadioButtonBuilder<B>> extends javafx.scene.control.ToggleButtonBuilder<B> {
    protected RadioButtonBuilder() {
    }

    /** Creates a new instance of RadioButtonBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.control.RadioButtonBuilder<?> create() {
        return new javafx.scene.control.RadioButtonBuilder();
    }

    /**
    Make an instance of {@link javafx.scene.control.RadioButton} based on the properties set on this builder.
    */
    public javafx.scene.control.RadioButton build() {
        javafx.scene.control.RadioButton x = new javafx.scene.control.RadioButton();
        applyTo(x);
        return x;
    }
}
