/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.control;

/**
Builder class for javafx.scene.control.RadioMenuItem
@see javafx.scene.control.RadioMenuItem
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class RadioMenuItemBuilder<B extends javafx.scene.control.RadioMenuItemBuilder<B>> extends javafx.scene.control.MenuItemBuilder<B> {
    protected RadioMenuItemBuilder() {
    }

    /** Creates a new instance of RadioMenuItemBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.control.RadioMenuItemBuilder<?> create() {
        return new javafx.scene.control.RadioMenuItemBuilder();
    }

    private int __set;
    public void applyTo(javafx.scene.control.RadioMenuItem x) {
        super.applyTo(x);
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setSelected(this.selected);
        if ((set & (1 << 1)) != 0) x.setToggleGroup(this.toggleGroup);
    }

    private boolean selected;
    /**
    Set the value of the {@link javafx.scene.control.RadioMenuItem#isSelected() selected} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B selected(boolean x) {
        this.selected = x;
        __set |= 1 << 0;
        return (B) this;
    }

    private java.lang.String text;
    /**
    Set the value of the {@link javafx.scene.control.RadioMenuItem#getText() text} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B text(java.lang.String x) {
        this.text = x;
        return (B) this;
    }

    private javafx.scene.control.ToggleGroup toggleGroup;
    /**
    Set the value of the {@link javafx.scene.control.RadioMenuItem#getToggleGroup() toggleGroup} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B toggleGroup(javafx.scene.control.ToggleGroup x) {
        this.toggleGroup = x;
        __set |= 1 << 1;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.scene.control.RadioMenuItem} based on the properties set on this builder.
    */
    public javafx.scene.control.RadioMenuItem build() {
        javafx.scene.control.RadioMenuItem x = new javafx.scene.control.RadioMenuItem(this.text);
        applyTo(x);
        return x;
    }
}
