/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.control;

/**
Builder class for javafx.scene.control.SplitMenuButton
@see javafx.scene.control.SplitMenuButton
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class SplitMenuButtonBuilder<B extends javafx.scene.control.SplitMenuButtonBuilder<B>> extends javafx.scene.control.MenuButtonBuilder<B> {
    protected SplitMenuButtonBuilder() {
    }

    /** Creates a new instance of SplitMenuButtonBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.control.SplitMenuButtonBuilder<?> create() {
        return new javafx.scene.control.SplitMenuButtonBuilder();
    }

    /**
    Make an instance of {@link javafx.scene.control.SplitMenuButton} based on the properties set on this builder.
    */
    public javafx.scene.control.SplitMenuButton build() {
        javafx.scene.control.SplitMenuButton x = new javafx.scene.control.SplitMenuButton();
        applyTo(x);
        return x;
    }
}
