/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.control;

/**
Builder class for javafx.scene.control.TableCell
@see javafx.scene.control.TableCell
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class TableCellBuilder<S, T, B extends javafx.scene.control.TableCellBuilder<S, T, B>> extends javafx.scene.control.CellBuilder<T, B> {
    protected TableCellBuilder() {
    }

    /** Creates a new instance of TableCellBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static <S, T> javafx.scene.control.TableCellBuilder<S, T, ?> create() {
        return new javafx.scene.control.TableCellBuilder();
    }

    /**
    Make an instance of {@link javafx.scene.control.TableCell} based on the properties set on this builder.
    */
    public javafx.scene.control.TableCell<S, T> build() {
        javafx.scene.control.TableCell<S, T> x = new javafx.scene.control.TableCell<S, T>();
        applyTo(x);
        return x;
    }
}
