/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.control;

/**
Builder class for javafx.scene.control.TablePosition
@see javafx.scene.control.TablePosition
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class TablePositionBuilder<S, T, B extends javafx.scene.control.TablePositionBuilder<S, T, B>> implements javafx.util.Builder<javafx.scene.control.TablePosition<S, T>> {
    protected TablePositionBuilder() {
    }

    /** Creates a new instance of TablePositionBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static <S, T> javafx.scene.control.TablePositionBuilder<S, T, ?> create() {
        return new javafx.scene.control.TablePositionBuilder();
    }

    private int row;
    /**
    Set the value of the {@link javafx.scene.control.TablePosition#getRow() row} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B row(int x) {
        this.row = x;
        return (B) this;
    }

    private javafx.scene.control.TableColumn<S,T> tableColumn;
    /**
    Set the value of the {@link javafx.scene.control.TablePosition#getTableColumn() tableColumn} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B tableColumn(javafx.scene.control.TableColumn<S,T> x) {
        this.tableColumn = x;
        return (B) this;
    }

    private javafx.scene.control.TableView<S> tableView;
    /**
    Set the value of the {@link javafx.scene.control.TablePosition#getTableView() tableView} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B tableView(javafx.scene.control.TableView<S> x) {
        this.tableView = x;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.scene.control.TablePosition} based on the properties set on this builder.
    */
    public javafx.scene.control.TablePosition<S, T> build() {
        javafx.scene.control.TablePosition<S, T> x = new javafx.scene.control.TablePosition<S, T>(this.tableView, this.row, this.tableColumn);
        return x;
    }
}
