/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.control;

/**
Builder class for javafx.scene.control.TextInputControl
@see javafx.scene.control.TextInputControl
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public abstract class TextInputControlBuilder<B extends javafx.scene.control.TextInputControlBuilder<B>> extends javafx.scene.control.ControlBuilder<B> {
    protected TextInputControlBuilder() {
    }


    private int __set;
    public void applyTo(javafx.scene.control.TextInputControl x) {
        super.applyTo(x);
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setEditable(this.editable);
        if ((set & (1 << 1)) != 0) x.setPromptText(this.promptText);
        if ((set & (1 << 2)) != 0) x.setText(this.text);
    }

    private boolean editable;
    /**
    Set the value of the {@link javafx.scene.control.TextInputControl#isEditable() editable} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B editable(boolean x) {
        this.editable = x;
        __set |= 1 << 0;
        return (B) this;
    }

    private java.lang.String promptText;
    /**
    Set the value of the {@link javafx.scene.control.TextInputControl#getPromptText() promptText} property for the instance constructed by this builder.
    * @since JavaFX 2.2
    */
    @SuppressWarnings("unchecked")
    public B promptText(java.lang.String x) {
        this.promptText = x;
        __set |= 1 << 1;
        return (B) this;
    }

    private java.lang.String text;
    /**
    Set the value of the {@link javafx.scene.control.TextInputControl#getText() text} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B text(java.lang.String x) {
        this.text = x;
        __set |= 1 << 2;
        return (B) this;
    }

}
