/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.control.cell;

/**
Builder class for javafx.scene.control.cell.TextFieldTableCell
@see javafx.scene.control.cell.TextFieldTableCell
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.2
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class TextFieldTableCellBuilder<S, T, B extends javafx.scene.control.cell.TextFieldTableCellBuilder<S, T, B>> extends javafx.scene.control.TableCellBuilder<S, T, B> {
    protected TextFieldTableCellBuilder() {
    }

    /** Creates a new instance of TextFieldTableCellBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static <S, T> javafx.scene.control.cell.TextFieldTableCellBuilder<S, T, ?> create() {
        return new javafx.scene.control.cell.TextFieldTableCellBuilder();
    }

    private boolean __set;
    public void applyTo(javafx.scene.control.cell.TextFieldTableCell<S, T> x) {
        super.applyTo(x);
        if (__set) x.setConverter(this.converter);
    }

    private javafx.util.StringConverter<T> converter;
    /**
    Set the value of the {@link javafx.scene.control.cell.TextFieldTableCell#getConverter() converter} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B converter(javafx.util.StringConverter<T> x) {
        this.converter = x;
        __set = true;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.scene.control.cell.TextFieldTableCell} based on the properties set on this builder.
    */
    public javafx.scene.control.cell.TextFieldTableCell<S, T> build() {
        javafx.scene.control.cell.TextFieldTableCell<S, T> x = new javafx.scene.control.cell.TextFieldTableCell<S, T>();
        applyTo(x);
        return x;
    }
}
