/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.stage;

/**
Builder class for javafx.stage.DirectoryChooser
@see javafx.stage.DirectoryChooser
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.1
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public final class DirectoryChooserBuilder implements javafx.util.Builder<javafx.stage.DirectoryChooser> {
    protected DirectoryChooserBuilder() {
    }

    /** Creates a new instance of DirectoryChooserBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.stage.DirectoryChooserBuilder create() {
        return new javafx.stage.DirectoryChooserBuilder();
    }

    private int __set;
    public void applyTo(javafx.stage.DirectoryChooser x) {
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setInitialDirectory(this.initialDirectory);
        if ((set & (1 << 1)) != 0) x.setTitle(this.title);
    }

    private java.io.File initialDirectory;
    /**
    Set the value of the {@link javafx.stage.DirectoryChooser#getInitialDirectory() initialDirectory} property for the instance constructed by this builder.
    */
    public javafx.stage.DirectoryChooserBuilder initialDirectory(java.io.File x) {
        this.initialDirectory = x;
        __set |= 1 << 0;
        return this;
    }

    private java.lang.String title;
    /**
    Set the value of the {@link javafx.stage.DirectoryChooser#getTitle() title} property for the instance constructed by this builder.
    */
    public javafx.stage.DirectoryChooserBuilder title(java.lang.String x) {
        this.title = x;
        __set |= 1 << 1;
        return this;
    }

    /**
    Make an instance of {@link javafx.stage.DirectoryChooser} based on the properties set on this builder.
    */
    public javafx.stage.DirectoryChooser build() {
        javafx.stage.DirectoryChooser x = new javafx.stage.DirectoryChooser();
        applyTo(x);
        return x;
    }
}
