/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.stage;

/**
Builder class for javafx.stage.PopupWindow
@see javafx.stage.PopupWindow
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public abstract class PopupWindowBuilder<B extends javafx.stage.PopupWindowBuilder<B>> extends javafx.stage.WindowBuilder<B> {
    protected PopupWindowBuilder() {
    }


    private int __set;
    public void applyTo(javafx.stage.PopupWindow x) {
        super.applyTo(x);
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setAutoFix(this.autoFix);
        if ((set & (1 << 1)) != 0) x.setAutoHide(this.autoHide);
        if ((set & (1 << 2)) != 0) x.setConsumeAutoHidingEvents(this.consumeAutoHidingEvents);
        if ((set & (1 << 3)) != 0) x.setHideOnEscape(this.hideOnEscape);
        if ((set & (1 << 4)) != 0) x.setOnAutoHide(this.onAutoHide);
    }

    private boolean autoFix;
    /**
    Set the value of the {@link javafx.stage.PopupWindow#isAutoFix() autoFix} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B autoFix(boolean x) {
        this.autoFix = x;
        __set |= 1 << 0;
        return (B) this;
    }

    private boolean autoHide;
    /**
    Set the value of the {@link javafx.stage.PopupWindow#isAutoHide() autoHide} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B autoHide(boolean x) {
        this.autoHide = x;
        __set |= 1 << 1;
        return (B) this;
    }

    private boolean consumeAutoHidingEvents;
    /**
    Set the value of the {@link javafx.stage.PopupWindow#getConsumeAutoHidingEvents() consumeAutoHidingEvents} property for the instance constructed by this builder.
    * @since JavaFX 2.2
    */
    @SuppressWarnings("unchecked")
    public B consumeAutoHidingEvents(boolean x) {
        this.consumeAutoHidingEvents = x;
        __set |= 1 << 2;
        return (B) this;
    }

    private boolean hideOnEscape;
    /**
    Set the value of the {@link javafx.stage.PopupWindow#isHideOnEscape() hideOnEscape} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B hideOnEscape(boolean x) {
        this.hideOnEscape = x;
        __set |= 1 << 3;
        return (B) this;
    }

    private javafx.event.EventHandler<javafx.event.Event> onAutoHide;
    /**
    Set the value of the {@link javafx.stage.PopupWindow#getOnAutoHide() onAutoHide} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B onAutoHide(javafx.event.EventHandler<javafx.event.Event> x) {
        this.onAutoHide = x;
        __set |= 1 << 4;
        return (B) this;
    }

}
