/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.animation;

/**
Builder class for javafx.animation.PathTransition
@see javafx.animation.PathTransition
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public final class PathTransitionBuilder extends javafx.animation.TransitionBuilder<javafx.animation.PathTransitionBuilder> implements javafx.util.Builder<javafx.animation.PathTransition> {
    protected PathTransitionBuilder() {
    }

    /** Creates a new instance of PathTransitionBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.animation.PathTransitionBuilder create() {
        return new javafx.animation.PathTransitionBuilder();
    }

    private int __set;
    public void applyTo(javafx.animation.PathTransition x) {
        super.applyTo(x);
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setDuration(this.duration);
        if ((set & (1 << 1)) != 0) x.setNode(this.node);
        if ((set & (1 << 2)) != 0) x.setOrientation(this.orientation);
        if ((set & (1 << 3)) != 0) x.setPath(this.path);
    }

    private javafx.util.Duration duration;
    /**
    Set the value of the {@link javafx.animation.PathTransition#getDuration() duration} property for the instance constructed by this builder.
    */
    public javafx.animation.PathTransitionBuilder duration(javafx.util.Duration x) {
        this.duration = x;
        __set |= 1 << 0;
        return this;
    }

    private javafx.scene.Node node;
    /**
    Set the value of the {@link javafx.animation.PathTransition#getNode() node} property for the instance constructed by this builder.
    */
    public javafx.animation.PathTransitionBuilder node(javafx.scene.Node x) {
        this.node = x;
        __set |= 1 << 1;
        return this;
    }

    private javafx.animation.PathTransition.OrientationType orientation;
    /**
    Set the value of the {@link javafx.animation.PathTransition#getOrientation() orientation} property for the instance constructed by this builder.
    */
    public javafx.animation.PathTransitionBuilder orientation(javafx.animation.PathTransition.OrientationType x) {
        this.orientation = x;
        __set |= 1 << 2;
        return this;
    }

    private javafx.scene.shape.Shape path;
    /**
    Set the value of the {@link javafx.animation.PathTransition#getPath() path} property for the instance constructed by this builder.
    */
    public javafx.animation.PathTransitionBuilder path(javafx.scene.shape.Shape x) {
        this.path = x;
        __set |= 1 << 3;
        return this;
    }

    /**
    Make an instance of {@link javafx.animation.PathTransition} based on the properties set on this builder.
    */
    public javafx.animation.PathTransition build() {
        javafx.animation.PathTransition x = new javafx.animation.PathTransition();
        applyTo(x);
        return x;
    }
}
