/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.animation;

/**
Builder class for javafx.animation.PauseTransition
@see javafx.animation.PauseTransition
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public final class PauseTransitionBuilder extends javafx.animation.TransitionBuilder<javafx.animation.PauseTransitionBuilder> implements javafx.util.Builder<javafx.animation.PauseTransition> {
    protected PauseTransitionBuilder() {
    }

    /** Creates a new instance of PauseTransitionBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.animation.PauseTransitionBuilder create() {
        return new javafx.animation.PauseTransitionBuilder();
    }

    private boolean __set;
    public void applyTo(javafx.animation.PauseTransition x) {
        super.applyTo(x);
        if (__set) x.setDuration(this.duration);
    }

    private javafx.util.Duration duration;
    /**
    Set the value of the {@link javafx.animation.PauseTransition#getDuration() duration} property for the instance constructed by this builder.
    */
    public javafx.animation.PauseTransitionBuilder duration(javafx.util.Duration x) {
        this.duration = x;
        __set = true;
        return this;
    }

    /**
    Make an instance of {@link javafx.animation.PauseTransition} based on the properties set on this builder.
    */
    public javafx.animation.PauseTransition build() {
        javafx.animation.PauseTransition x = new javafx.animation.PauseTransition();
        applyTo(x);
        return x;
    }
}
