/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.animation;

/**
Builder class for javafx.animation.SequentialTransition
@see javafx.animation.SequentialTransition
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public final class SequentialTransitionBuilder extends javafx.animation.TransitionBuilder<javafx.animation.SequentialTransitionBuilder> implements javafx.util.Builder<javafx.animation.SequentialTransition> {
    protected SequentialTransitionBuilder() {
    }

    /** Creates a new instance of SequentialTransitionBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.animation.SequentialTransitionBuilder create() {
        return new javafx.animation.SequentialTransitionBuilder();
    }

    private int __set;
    public void applyTo(javafx.animation.SequentialTransition x) {
        super.applyTo(x);
        int set = __set;
        if ((set & (1 << 0)) != 0) x.getChildren().addAll(this.children);
        if ((set & (1 << 1)) != 0) x.setNode(this.node);
    }

    private java.util.Collection<? extends javafx.animation.Animation> children;
    /**
    Add the given items to the List of items in the {@link javafx.animation.SequentialTransition#getChildren() children} property for the instance constructed by this builder.
    */
    public javafx.animation.SequentialTransitionBuilder children(java.util.Collection<? extends javafx.animation.Animation> x) {
        this.children = x;
        __set |= 1 << 0;
        return this;
    }

    /**
    Add the given items to the List of items in the {@link javafx.animation.SequentialTransition#getChildren() children} property for the instance constructed by this builder.
    */
    public javafx.animation.SequentialTransitionBuilder children(javafx.animation.Animation... x) {
        return children(java.util.Arrays.asList(x));
    }

    private javafx.scene.Node node;
    /**
    Set the value of the {@link javafx.animation.SequentialTransition#getNode() node} property for the instance constructed by this builder.
    */
    public javafx.animation.SequentialTransitionBuilder node(javafx.scene.Node x) {
        this.node = x;
        __set |= 1 << 1;
        return this;
    }

    /**
    Make an instance of {@link javafx.animation.SequentialTransition} based on the properties set on this builder.
    */
    public javafx.animation.SequentialTransition build() {
        javafx.animation.SequentialTransition x = new javafx.animation.SequentialTransition();
        applyTo(x);
        return x;
    }
}
