/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.animation;

/**
Builder class for javafx.animation.Timeline
@see javafx.animation.Timeline
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public final class TimelineBuilder extends javafx.animation.AnimationBuilder<javafx.animation.TimelineBuilder> implements javafx.util.Builder<javafx.animation.Timeline> {
    protected TimelineBuilder() {
    }

    /** Creates a new instance of TimelineBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.animation.TimelineBuilder create() {
        return new javafx.animation.TimelineBuilder();
    }

    private boolean __set;
    public void applyTo(javafx.animation.Timeline x) {
        super.applyTo(x);
        if (__set) x.getKeyFrames().addAll(this.keyFrames);
    }

    private java.util.Collection<? extends javafx.animation.KeyFrame> keyFrames;
    /**
    Add the given items to the List of items in the {@link javafx.animation.Timeline#getKeyFrames() keyFrames} property for the instance constructed by this builder.
    */
    public javafx.animation.TimelineBuilder keyFrames(java.util.Collection<? extends javafx.animation.KeyFrame> x) {
        this.keyFrames = x;
        __set = true;
        return this;
    }

    /**
    Add the given items to the List of items in the {@link javafx.animation.Timeline#getKeyFrames() keyFrames} property for the instance constructed by this builder.
    */
    public javafx.animation.TimelineBuilder keyFrames(javafx.animation.KeyFrame... x) {
        return keyFrames(java.util.Arrays.asList(x));
    }

    private double targetFramerate;
    /**
    Set the value of the {@link javafx.animation.Timeline#getTargetFramerate() targetFramerate} property for the instance constructed by this builder.
    */
    public javafx.animation.TimelineBuilder targetFramerate(double x) {
        this.targetFramerate = x;
        return this;
    }

    /**
    Make an instance of {@link javafx.animation.Timeline} based on the properties set on this builder.
    */
    public javafx.animation.Timeline build() {
        javafx.animation.Timeline x = new javafx.animation.Timeline(this.targetFramerate);
        applyTo(x);
        return x;
    }
}
