/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.animation;

/**
Builder class for javafx.animation.Transition
@see javafx.animation.Transition
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public abstract class TransitionBuilder<B extends javafx.animation.TransitionBuilder<B>> extends javafx.animation.AnimationBuilder<B> {
    protected TransitionBuilder() {
    }


    private boolean __set;
    public void applyTo(javafx.animation.Transition x) {
        super.applyTo(x);
        if (__set) x.setInterpolator(this.interpolator);
    }

    private javafx.animation.Interpolator interpolator;
    /**
    Set the value of the {@link javafx.animation.Transition#getInterpolator() interpolator} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B interpolator(javafx.animation.Interpolator x) {
        this.interpolator = x;
        __set = true;
        return (B) this;
    }

    private double targetFramerate;
    /**
    Set the value of the {@link javafx.animation.Transition#getTargetFramerate() targetFramerate} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B targetFramerate(double x) {
        this.targetFramerate = x;
        return (B) this;
    }

}
