/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.chart;

/**
Builder class for javafx.scene.chart.Chart
@see javafx.scene.chart.Chart
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public abstract class ChartBuilder<B extends javafx.scene.chart.ChartBuilder<B>> extends javafx.scene.layout.RegionBuilder<B> {
    protected ChartBuilder() {
    }


    private int __set;
    public void applyTo(javafx.scene.chart.Chart x) {
        super.applyTo(x);
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setAnimated(this.animated);
        if ((set & (1 << 1)) != 0) x.setLegendSide(this.legendSide);
        if ((set & (1 << 2)) != 0) x.setLegendVisible(this.legendVisible);
        if ((set & (1 << 3)) != 0) x.setTitle(this.title);
        if ((set & (1 << 4)) != 0) x.setTitleSide(this.titleSide);
    }

    private boolean animated;
    /**
    Set the value of the {@link javafx.scene.chart.Chart#getAnimated() animated} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B animated(boolean x) {
        this.animated = x;
        __set |= 1 << 0;
        return (B) this;
    }

    private javafx.geometry.Side legendSide;
    /**
    Set the value of the {@link javafx.scene.chart.Chart#getLegendSide() legendSide} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B legendSide(javafx.geometry.Side x) {
        this.legendSide = x;
        __set |= 1 << 1;
        return (B) this;
    }

    private boolean legendVisible;
    /**
    Set the value of the {@link javafx.scene.chart.Chart#isLegendVisible() legendVisible} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B legendVisible(boolean x) {
        this.legendVisible = x;
        __set |= 1 << 2;
        return (B) this;
    }

    private java.lang.String title;
    /**
    Set the value of the {@link javafx.scene.chart.Chart#getTitle() title} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B title(java.lang.String x) {
        this.title = x;
        __set |= 1 << 3;
        return (B) this;
    }

    private javafx.geometry.Side titleSide;
    /**
    Set the value of the {@link javafx.scene.chart.Chart#getTitleSide() titleSide} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B titleSide(javafx.geometry.Side x) {
        this.titleSide = x;
        __set |= 1 << 4;
        return (B) this;
    }

}
