/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.geometry;

/**
Builder class for javafx.geometry.Point3D
@see javafx.geometry.Point3D
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class Point3DBuilder<B extends javafx.geometry.Point3DBuilder<B>> implements javafx.util.Builder<javafx.geometry.Point3D> {
    protected Point3DBuilder() {
    }

    /** Creates a new instance of Point3DBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.geometry.Point3DBuilder<?> create() {
        return new javafx.geometry.Point3DBuilder();
    }

    private double x;
    /**
    Set the value of the {@link javafx.geometry.Point3D#getX() x} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B x(double x) {
        this.x = x;
        return (B) this;
    }

    private double y;
    /**
    Set the value of the {@link javafx.geometry.Point3D#getY() y} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B y(double x) {
        this.y = x;
        return (B) this;
    }

    private double z;
    /**
    Set the value of the {@link javafx.geometry.Point3D#getZ() z} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B z(double x) {
        this.z = x;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.geometry.Point3D} based on the properties set on this builder.
    */
    public javafx.geometry.Point3D build() {
        javafx.geometry.Point3D x = new javafx.geometry.Point3D(this.x, this.y, this.z);
        return x;
    }
}
