/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.geometry;

/**
Builder class for javafx.geometry.Point2D
@see javafx.geometry.Point2D
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class Point2DBuilder<B extends javafx.geometry.Point2DBuilder<B>> implements javafx.util.Builder<javafx.geometry.Point2D> {
    protected Point2DBuilder() {
    }

    /** Creates a new instance of Point2DBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.geometry.Point2DBuilder<?> create() {
        return new javafx.geometry.Point2DBuilder();
    }

    private double x;
    /**
    Set the value of the {@link javafx.geometry.Point2D#getX() x} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B x(double x) {
        this.x = x;
        return (B) this;
    }

    private double y;
    /**
    Set the value of the {@link javafx.geometry.Point2D#getY() y} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B y(double x) {
        this.y = x;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.geometry.Point2D} based on the properties set on this builder.
    */
    public javafx.geometry.Point2D build() {
        javafx.geometry.Point2D x = new javafx.geometry.Point2D(this.x, this.y);
        return x;
    }
}
