/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.transform;

/**
Builder class for javafx.scene.transform.Translate
@see javafx.scene.transform.Translate
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class TranslateBuilder<B extends javafx.scene.transform.TranslateBuilder<B>> implements javafx.util.Builder<javafx.scene.transform.Translate> {
    protected TranslateBuilder() {
    }

    /** Creates a new instance of TranslateBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.transform.TranslateBuilder<?> create() {
        return new javafx.scene.transform.TranslateBuilder();
    }

    private int __set;
    public void applyTo(javafx.scene.transform.Translate x) {
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setX(this.x);
        if ((set & (1 << 1)) != 0) x.setY(this.y);
        if ((set & (1 << 2)) != 0) x.setZ(this.z);
    }

    private double x;
    /**
    Set the value of the {@link javafx.scene.transform.Translate#getX() x} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B x(double x) {
        this.x = x;
        __set |= 1 << 0;
        return (B) this;
    }

    private double y;
    /**
    Set the value of the {@link javafx.scene.transform.Translate#getY() y} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B y(double x) {
        this.y = x;
        __set |= 1 << 1;
        return (B) this;
    }

    private double z;
    /**
    Set the value of the {@link javafx.scene.transform.Translate#getZ() z} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B z(double x) {
        this.z = x;
        __set |= 1 << 2;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.scene.transform.Translate} based on the properties set on this builder.
    */
    public javafx.scene.transform.Translate build() {
        javafx.scene.transform.Translate x = new javafx.scene.transform.Translate();
        applyTo(x);
        return x;
    }
}
