/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.paint;

/**
Builder class for javafx.scene.paint.Stop
@see javafx.scene.paint.Stop
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public final class StopBuilder implements javafx.util.Builder<javafx.scene.paint.Stop> {
    protected StopBuilder() {
    }

    /** Creates a new instance of StopBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.paint.StopBuilder create() {
        return new javafx.scene.paint.StopBuilder();
    }

    private javafx.scene.paint.Color color = javafx.scene.paint.Color.BLACK;
    /**
    Set the value of the {@link javafx.scene.paint.Stop#getColor() color} property for the instance constructed by this builder.
    */
    public javafx.scene.paint.StopBuilder color(javafx.scene.paint.Color x) {
        this.color = x;
        return this;
    }

    private double offset;
    /**
    Set the value of the {@link javafx.scene.paint.Stop#getOffset() offset} property for the instance constructed by this builder.
    */
    public javafx.scene.paint.StopBuilder offset(double x) {
        this.offset = x;
        return this;
    }

    /**
    Make an instance of {@link javafx.scene.paint.Stop} based on the properties set on this builder.
    */
    public javafx.scene.paint.Stop build() {
        javafx.scene.paint.Stop x = new javafx.scene.paint.Stop(this.offset, this.color);
        return x;
    }
}
