/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.shape;

/**
Builder class for javafx.scene.shape.ClosePath
@see javafx.scene.shape.ClosePath
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class ClosePathBuilder<B extends javafx.scene.shape.ClosePathBuilder<B>> extends javafx.scene.shape.PathElementBuilder<B> implements javafx.util.Builder<javafx.scene.shape.ClosePath> {
    protected ClosePathBuilder() {
    }

    /** Creates a new instance of ClosePathBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.shape.ClosePathBuilder<?> create() {
        return new javafx.scene.shape.ClosePathBuilder();
    }

    /**
    Make an instance of {@link javafx.scene.shape.ClosePath} based on the properties set on this builder.
    */
    public javafx.scene.shape.ClosePath build() {
        javafx.scene.shape.ClosePath x = new javafx.scene.shape.ClosePath();
        applyTo(x);
        return x;
    }
}
