/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.shape;

/**
Builder class for javafx.scene.shape.Path
@see javafx.scene.shape.Path
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class PathBuilder<B extends javafx.scene.shape.PathBuilder<B>> extends javafx.scene.shape.ShapeBuilder<B> implements javafx.util.Builder<javafx.scene.shape.Path> {
    protected PathBuilder() {
    }

    /** Creates a new instance of PathBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.shape.PathBuilder<?> create() {
        return new javafx.scene.shape.PathBuilder();
    }

    private int __set;
    public void applyTo(javafx.scene.shape.Path x) {
        super.applyTo(x);
        int set = __set;
        if ((set & (1 << 0)) != 0) x.getElements().addAll(this.elements);
        if ((set & (1 << 1)) != 0) x.setFillRule(this.fillRule);
    }

    private java.util.Collection<? extends javafx.scene.shape.PathElement> elements;
    /**
    Add the given items to the List of items in the {@link javafx.scene.shape.Path#getElements() elements} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B elements(java.util.Collection<? extends javafx.scene.shape.PathElement> x) {
        this.elements = x;
        __set |= 1 << 0;
        return (B) this;
    }

    /**
    Add the given items to the List of items in the {@link javafx.scene.shape.Path#getElements() elements} property for the instance constructed by this builder.
    */
    public B elements(javafx.scene.shape.PathElement... x) {
        return elements(java.util.Arrays.asList(x));
    }

    private javafx.scene.shape.FillRule fillRule;
    /**
    Set the value of the {@link javafx.scene.shape.Path#getFillRule() fillRule} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B fillRule(javafx.scene.shape.FillRule x) {
        this.fillRule = x;
        __set |= 1 << 1;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.scene.shape.Path} based on the properties set on this builder.
    */
    public javafx.scene.shape.Path build() {
        javafx.scene.shape.Path x = new javafx.scene.shape.Path();
        applyTo(x);
        return x;
    }
}
