/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.shape;

/**
Builder class for javafx.scene.shape.QuadCurveTo
@see javafx.scene.shape.QuadCurveTo
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class QuadCurveToBuilder<B extends javafx.scene.shape.QuadCurveToBuilder<B>> extends javafx.scene.shape.PathElementBuilder<B> implements javafx.util.Builder<javafx.scene.shape.QuadCurveTo> {
    protected QuadCurveToBuilder() {
    }

    /** Creates a new instance of QuadCurveToBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.shape.QuadCurveToBuilder<?> create() {
        return new javafx.scene.shape.QuadCurveToBuilder();
    }

    private int __set;
    public void applyTo(javafx.scene.shape.QuadCurveTo x) {
        super.applyTo(x);
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setControlX(this.controlX);
        if ((set & (1 << 1)) != 0) x.setControlY(this.controlY);
        if ((set & (1 << 2)) != 0) x.setX(this.x);
        if ((set & (1 << 3)) != 0) x.setY(this.y);
    }

    private double controlX;
    /**
    Set the value of the {@link javafx.scene.shape.QuadCurveTo#getControlX() controlX} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B controlX(double x) {
        this.controlX = x;
        __set |= 1 << 0;
        return (B) this;
    }

    private double controlY;
    /**
    Set the value of the {@link javafx.scene.shape.QuadCurveTo#getControlY() controlY} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B controlY(double x) {
        this.controlY = x;
        __set |= 1 << 1;
        return (B) this;
    }

    private double x;
    /**
    Set the value of the {@link javafx.scene.shape.QuadCurveTo#getX() x} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B x(double x) {
        this.x = x;
        __set |= 1 << 2;
        return (B) this;
    }

    private double y;
    /**
    Set the value of the {@link javafx.scene.shape.QuadCurveTo#getY() y} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B y(double x) {
        this.y = x;
        __set |= 1 << 3;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.scene.shape.QuadCurveTo} based on the properties set on this builder.
    */
    public javafx.scene.shape.QuadCurveTo build() {
        javafx.scene.shape.QuadCurveTo x = new javafx.scene.shape.QuadCurveTo();
        applyTo(x);
        return x;
    }
}
