/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.shape;

/**
Builder class for javafx.scene.shape.SVGPath
@see javafx.scene.shape.SVGPath
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class SVGPathBuilder<B extends javafx.scene.shape.SVGPathBuilder<B>> extends javafx.scene.shape.ShapeBuilder<B> implements javafx.util.Builder<javafx.scene.shape.SVGPath> {
    protected SVGPathBuilder() {
    }

    /** Creates a new instance of SVGPathBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.shape.SVGPathBuilder<?> create() {
        return new javafx.scene.shape.SVGPathBuilder();
    }

    private int __set;
    public void applyTo(javafx.scene.shape.SVGPath x) {
        super.applyTo(x);
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setContent(this.content);
        if ((set & (1 << 1)) != 0) x.setFillRule(this.fillRule);
    }

    private java.lang.String content;
    /**
    Set the value of the {@link javafx.scene.shape.SVGPath#getContent() content} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B content(java.lang.String x) {
        this.content = x;
        __set |= 1 << 0;
        return (B) this;
    }

    private javafx.scene.shape.FillRule fillRule;
    /**
    Set the value of the {@link javafx.scene.shape.SVGPath#getFillRule() fillRule} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B fillRule(javafx.scene.shape.FillRule x) {
        this.fillRule = x;
        __set |= 1 << 1;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.scene.shape.SVGPath} based on the properties set on this builder.
    */
    public javafx.scene.shape.SVGPath build() {
        javafx.scene.shape.SVGPath x = new javafx.scene.shape.SVGPath();
        applyTo(x);
        return x;
    }
}
