/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.shape;

/**
Builder class for javafx.scene.shape.VLineTo
@see javafx.scene.shape.VLineTo
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class VLineToBuilder<B extends javafx.scene.shape.VLineToBuilder<B>> extends javafx.scene.shape.PathElementBuilder<B> implements javafx.util.Builder<javafx.scene.shape.VLineTo> {
    protected VLineToBuilder() {
    }

    /** Creates a new instance of VLineToBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.shape.VLineToBuilder<?> create() {
        return new javafx.scene.shape.VLineToBuilder();
    }

    private boolean __set;
    public void applyTo(javafx.scene.shape.VLineTo x) {
        super.applyTo(x);
        if (__set) x.setY(this.y);
    }

    private double y;
    /**
    Set the value of the {@link javafx.scene.shape.VLineTo#getY() y} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B y(double x) {
        this.y = x;
        __set = true;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.scene.shape.VLineTo} based on the properties set on this builder.
    */
    public javafx.scene.shape.VLineTo build() {
        javafx.scene.shape.VLineTo x = new javafx.scene.shape.VLineTo();
        applyTo(x);
        return x;
    }
}
