/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.layout;

/**
Builder class for javafx.scene.layout.AnchorPane
@see javafx.scene.layout.AnchorPane
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class AnchorPaneBuilder<B extends javafx.scene.layout.AnchorPaneBuilder<B>> extends javafx.scene.layout.PaneBuilder<B> {
    protected AnchorPaneBuilder() {
    }

    /** Creates a new instance of AnchorPaneBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.layout.AnchorPaneBuilder<?> create() {
        return new javafx.scene.layout.AnchorPaneBuilder();
    }

    /**
    Make an instance of {@link javafx.scene.layout.AnchorPane} based on the properties set on this builder.
    */
    public javafx.scene.layout.AnchorPane build() {
        javafx.scene.layout.AnchorPane x = new javafx.scene.layout.AnchorPane();
        applyTo(x);
        return x;
    }
}
