/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.layout;

/**
Builder class for javafx.scene.layout.BorderPane
@see javafx.scene.layout.BorderPane
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class BorderPaneBuilder<B extends javafx.scene.layout.BorderPaneBuilder<B>> extends javafx.scene.layout.PaneBuilder<B> {
    protected BorderPaneBuilder() {
    }

    /** Creates a new instance of BorderPaneBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.layout.BorderPaneBuilder<?> create() {
        return new javafx.scene.layout.BorderPaneBuilder();
    }

    private int __set;
    public void applyTo(javafx.scene.layout.BorderPane x) {
        super.applyTo(x);
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setBottom(this.bottom);
        if ((set & (1 << 1)) != 0) x.setCenter(this.center);
        if ((set & (1 << 2)) != 0) x.setLeft(this.left);
        if ((set & (1 << 3)) != 0) x.setRight(this.right);
        if ((set & (1 << 4)) != 0) x.setTop(this.top);
    }

    private javafx.scene.Node bottom;
    /**
    Set the value of the {@link javafx.scene.layout.BorderPane#getBottom() bottom} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B bottom(javafx.scene.Node x) {
        this.bottom = x;
        __set |= 1 << 0;
        return (B) this;
    }

    private javafx.scene.Node center;
    /**
    Set the value of the {@link javafx.scene.layout.BorderPane#getCenter() center} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B center(javafx.scene.Node x) {
        this.center = x;
        __set |= 1 << 1;
        return (B) this;
    }

    private javafx.scene.Node left;
    /**
    Set the value of the {@link javafx.scene.layout.BorderPane#getLeft() left} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B left(javafx.scene.Node x) {
        this.left = x;
        __set |= 1 << 2;
        return (B) this;
    }

    private javafx.scene.Node right;
    /**
    Set the value of the {@link javafx.scene.layout.BorderPane#getRight() right} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B right(javafx.scene.Node x) {
        this.right = x;
        __set |= 1 << 3;
        return (B) this;
    }

    private javafx.scene.Node top;
    /**
    Set the value of the {@link javafx.scene.layout.BorderPane#getTop() top} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B top(javafx.scene.Node x) {
        this.top = x;
        __set |= 1 << 4;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.scene.layout.BorderPane} based on the properties set on this builder.
    */
    public javafx.scene.layout.BorderPane build() {
        javafx.scene.layout.BorderPane x = new javafx.scene.layout.BorderPane();
        applyTo(x);
        return x;
    }
}
