/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.layout;

/**
Builder class for javafx.scene.layout.StackPane
@see javafx.scene.layout.StackPane
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class StackPaneBuilder<B extends javafx.scene.layout.StackPaneBuilder<B>> extends javafx.scene.layout.PaneBuilder<B> {
    protected StackPaneBuilder() {
    }

    /** Creates a new instance of StackPaneBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.layout.StackPaneBuilder<?> create() {
        return new javafx.scene.layout.StackPaneBuilder();
    }

    private boolean __set;
    public void applyTo(javafx.scene.layout.StackPane x) {
        super.applyTo(x);
        if (__set) x.setAlignment(this.alignment);
    }

    private javafx.geometry.Pos alignment;
    /**
    Set the value of the {@link javafx.scene.layout.StackPane#getAlignment() alignment} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B alignment(javafx.geometry.Pos x) {
        this.alignment = x;
        __set = true;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.scene.layout.StackPane} based on the properties set on this builder.
    */
    public javafx.scene.layout.StackPane build() {
        javafx.scene.layout.StackPane x = new javafx.scene.layout.StackPane();
        applyTo(x);
        return x;
    }
}
