/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.effect;

/**
Builder class for javafx.scene.effect.Bloom
@see javafx.scene.effect.Bloom
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class BloomBuilder<B extends javafx.scene.effect.BloomBuilder<B>> implements javafx.util.Builder<javafx.scene.effect.Bloom> {
    protected BloomBuilder() {
    }

    /** Creates a new instance of BloomBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.effect.BloomBuilder<?> create() {
        return new javafx.scene.effect.BloomBuilder();
    }

    private int __set;
    public void applyTo(javafx.scene.effect.Bloom x) {
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setInput(this.input);
        if ((set & (1 << 1)) != 0) x.setThreshold(this.threshold);
    }

    private javafx.scene.effect.Effect input;
    /**
    Set the value of the {@link javafx.scene.effect.Bloom#getInput() input} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B input(javafx.scene.effect.Effect x) {
        this.input = x;
        __set |= 1 << 0;
        return (B) this;
    }

    private double threshold;
    /**
    Set the value of the {@link javafx.scene.effect.Bloom#getThreshold() threshold} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B threshold(double x) {
        this.threshold = x;
        __set |= 1 << 1;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.scene.effect.Bloom} based on the properties set on this builder.
    */
    public javafx.scene.effect.Bloom build() {
        javafx.scene.effect.Bloom x = new javafx.scene.effect.Bloom();
        applyTo(x);
        return x;
    }
}
