/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.effect;

/**
Builder class for javafx.scene.effect.Glow
@see javafx.scene.effect.Glow
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class GlowBuilder<B extends javafx.scene.effect.GlowBuilder<B>> implements javafx.util.Builder<javafx.scene.effect.Glow> {
    protected GlowBuilder() {
    }

    /** Creates a new instance of GlowBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.effect.GlowBuilder<?> create() {
        return new javafx.scene.effect.GlowBuilder();
    }

    private int __set;
    public void applyTo(javafx.scene.effect.Glow x) {
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setInput(this.input);
        if ((set & (1 << 1)) != 0) x.setLevel(this.level);
    }

    private javafx.scene.effect.Effect input;
    /**
    Set the value of the {@link javafx.scene.effect.Glow#getInput() input} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B input(javafx.scene.effect.Effect x) {
        this.input = x;
        __set |= 1 << 0;
        return (B) this;
    }

    private double level;
    /**
    Set the value of the {@link javafx.scene.effect.Glow#getLevel() level} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B level(double x) {
        this.level = x;
        __set |= 1 << 1;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.scene.effect.Glow} based on the properties set on this builder.
    */
    public javafx.scene.effect.Glow build() {
        javafx.scene.effect.Glow x = new javafx.scene.effect.Glow();
        applyTo(x);
        return x;
    }
}
