/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.effect;

/**
Builder class for javafx.scene.effect.Light
@see javafx.scene.effect.Light
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public abstract class LightBuilder<B extends javafx.scene.effect.LightBuilder<B>> {
    protected LightBuilder() {
    }


    private boolean __set;
    public void applyTo(javafx.scene.effect.Light x) {
        if (__set) x.setColor(this.color);
    }

    private javafx.scene.paint.Color color;
    /**
    Set the value of the {@link javafx.scene.effect.Light#getColor() color} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B color(javafx.scene.paint.Color x) {
        this.color = x;
        __set = true;
        return (B) this;
    }

}
