/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.effect;

/**
Builder class for javafx.scene.effect.MotionBlur
@see javafx.scene.effect.MotionBlur
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class MotionBlurBuilder<B extends javafx.scene.effect.MotionBlurBuilder<B>> implements javafx.util.Builder<javafx.scene.effect.MotionBlur> {
    protected MotionBlurBuilder() {
    }

    /** Creates a new instance of MotionBlurBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.effect.MotionBlurBuilder<?> create() {
        return new javafx.scene.effect.MotionBlurBuilder();
    }

    private int __set;
    public void applyTo(javafx.scene.effect.MotionBlur x) {
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setAngle(this.angle);
        if ((set & (1 << 1)) != 0) x.setInput(this.input);
        if ((set & (1 << 2)) != 0) x.setRadius(this.radius);
    }

    private double angle;
    /**
    Set the value of the {@link javafx.scene.effect.MotionBlur#getAngle() angle} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B angle(double x) {
        this.angle = x;
        __set |= 1 << 0;
        return (B) this;
    }

    private javafx.scene.effect.Effect input;
    /**
    Set the value of the {@link javafx.scene.effect.MotionBlur#getInput() input} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B input(javafx.scene.effect.Effect x) {
        this.input = x;
        __set |= 1 << 1;
        return (B) this;
    }

    private double radius;
    /**
    Set the value of the {@link javafx.scene.effect.MotionBlur#getRadius() radius} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B radius(double x) {
        this.radius = x;
        __set |= 1 << 2;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.scene.effect.MotionBlur} based on the properties set on this builder.
    */
    public javafx.scene.effect.MotionBlur build() {
        javafx.scene.effect.MotionBlur x = new javafx.scene.effect.MotionBlur();
        applyTo(x);
        return x;
    }
}
