/*
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package javafx.scene.effect;

/**
Builder class for javafx.scene.effect.SepiaTone
@see javafx.scene.effect.SepiaTone
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class SepiaToneBuilder<B extends javafx.scene.effect.SepiaToneBuilder<B>> implements javafx.util.Builder<javafx.scene.effect.SepiaTone> {
    protected SepiaToneBuilder() {
    }

    /** Creates a new instance of SepiaToneBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.effect.SepiaToneBuilder<?> create() {
        return new javafx.scene.effect.SepiaToneBuilder();
    }

    private int __set;
    public void applyTo(javafx.scene.effect.SepiaTone x) {
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setInput(this.input);
        if ((set & (1 << 1)) != 0) x.setLevel(this.level);
    }

    private javafx.scene.effect.Effect input;
    /**
    Set the value of the {@link javafx.scene.effect.SepiaTone#getInput() input} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B input(javafx.scene.effect.Effect x) {
        this.input = x;
        __set |= 1 << 0;
        return (B) this;
    }

    private double level;
    /**
    Set the value of the {@link javafx.scene.effect.SepiaTone#getLevel() level} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B level(double x) {
        this.level = x;
        __set |= 1 << 1;
        return (B) this;
    }

    /**
    Make an instance of {@link javafx.scene.effect.SepiaTone} based on the properties set on this builder.
    */
    public javafx.scene.effect.SepiaTone build() {
        javafx.scene.effect.SepiaTone x = new javafx.scene.effect.SepiaTone();
        applyTo(x);
        return x;
    }
}
